export default [
    {
        id: 1,
        title: "Life lessons with Katie Zaferes",
        description: "X",
        price: 136,
        img: "/swimmer.jpg",
        alt: "swimmer-picture",
        available: 0,
        stats: {
            rating: 5.0,
            reviewCount: 6,
        },
        location: "USA",
    },
    {
        id: 2,
        title: "Learn wedding photography",
        description: "X",
        price: 125,
        img: "/woman.jpg",
        alt: "woman-picture",
        available: 72,
        stats: {
            rating: 4.8,
            reviewCount: 30,
        },
        location: "PARIS",
    },
    {
        id: 3,
        title: "Group Mountain Biking",
        description: "X",
        price: 50,
        img: "/bike.jpg",
        alt: "bike-picture",
        stats: {
            rating: 4.0,
            reviewCount: 4,
        },
        location: "USA",
    },
    {
        id: 1,
        title: "Life lessons with Katie Zaferes",
        description: "X",
        price: 136,
        img: "/swimmer.jpg",
        alt: "swimmer-picture",
        available: 0,
        stats: {
            rating: 5.0,
            reviewCount: 6,
        },
        location: "USA",
    },
    {
        id: 2,
        title: "Learn wedding photography",
        description: "X",
        price: 125,
        img: "/woman.jpg",
        alt: "woman-picture",
        available: 72,
        stats: {
            rating: 4.8,
            reviewCount: 30,
        },
        location: "PARIS",
    },
    {
        id: 3,
        title: "Group Mountain Biking",
        description: "X",
        price: 50,
        img: "/bike.jpg",
        alt: "bike-picture",
        stats: {
            rating: 4.0,
            reviewCount: 4,
        },
        location: "USA",
    },
];
